server:
  port: 8000

zuul:
  prefix: /api
  routes:
    multiplications:
      path: /multiplications/**
      url: http://localhost:8080/multiplications
      strip-prefix: false
    results:
      path: /results/**
      url: http://localhost:8080/results
      strip-prefix: false
    leaders:
      path: /leaders/**
      url: http://localhost:8081/leaders
      strip-prefix: false
    stats:
      path: /stats/**
      url: http://localhost:8081/stats
      strip-prefix: false

  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  ignored-services: '*'

endpoint:
  routes:
    sensitive: false

  trace:
    sensitive: false

ribbon:
  eureka:
    enabled: false

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

