server:
  port: 8000

zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    multiplications:
      path: /multiplications/**
      serviceId: springboot-microservices
#      url: http://localhost:8080/multiplications
      strip-prefix: false
    results:
      path: /results/**
      serviceId: springboot-microservices
#      url: http://localhost:8080/results
      strip-prefix: false
    leaders:
      path: /leaders/**
      serviceId: gamification
#      url: http://localhost:8081/leaders
      strip-prefix: false
    stats:
      path: /stats/**
      serviceId: gamification
#      url: http://localhost:8081/stats
      strip-prefix: false

  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin

endpoint:
  routes:
    sensitive: false

  trace:
    sensitive: false

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

