spring:
  h2:
    console:
      enabled: true #H2 DB Access Web Console

  jpa:
    hibernate:
      ddl-auto: update #If DB is not exist Create Database
    properties:
      hibernate:
        show_sql: true #Show SQL in the console

  datasource :
    url: jdbc:h2:file:~/social-multiplication;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE #Create database to file

multiplication:
  exchange: multiplication_exchange

  solved:
    key: multiplication.solved


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
server:
  port: 8080
