server:
  address: localhost
  port: 8081

multiplication:
  exchange: multiplication_exchange

  solved:
    key: multiplication.solved

  queue: gamification_multiplication_queue

  anything:
    routing-key: multiplication.*


multiplicationHost: http://localhost:8000/api
